Make the script a proper application
Add command line options and usage instructions.

Also add support for specifying different radix bases for input/output.

Remove unused functions.

diff --git a/modexp b/modexp
--- a/modexp
+++ b/modexp
@@ -1,15 +1,86 @@
 #! /bin/sh
 set -e
-test 'test $? = 0 || echo "$0 failed!" >& 2'
-awk -f - -- "$@" << EOF && exit || false || exit
-	function vinternal() {
+exit_version() {
+	cat << EOF; exit # Text width: 66 columns.
+$APPLICATION_NAME Version 2017.222
+
+Copyright (c) 2017 Guenther Brunthaler. All rights reserved.
+
+This script is free software.
+Distribution is permitted under the terms of the GPLv3.
+EOF
+}
+APPLICATION_NAME=$0
+
+exit_help() {
+	cat << EOF; echo; exit_version # Text width: 66 columns.
+$APPLICATION_NAME - sufficiently efficient modular exponentiation
+
+Calculate (<base> ** <exponent>) modulo <modulus> with sufficient
+efficiency even for very large numbers, such as those required in
+the Diffie-Hellman key exchange protocol.
+
+Usage: $APPLICATION_NAME <base> <exponent> <modulus>
+
+Options:
+
+-b <base>:
+   Specify a radix base between 2 and 36 for input/output.
+   Defaults to 0 if omitted. The value 0 means automatic input
+   radix base detection and a fixed output radix of 10.
+-A <awk_cmd>
+   Invoke <awk_cmd> internally rather than the default "awk". For
+   example, <awk_cmd> could be "busybox awk".
+-h: Display this help and exit
+-V: Display version information and exit
+
+Automatic input radix base detection:
+
+Without option -b or with option -b0, every argument defaults to
+radix base 10 but the following argument prefixes can be used to
+override the base individually:
+
+* "0x" and "0X" selects base 16.
+* "0o" and "0O" selects base 8.
+* "0b" and "0B" selects base 2.
+* "0r<base> and "0r<base>:" selects base <base> (<base> itself
+  must be specified as a decimal number between 1 and 36)
+EOF
+}
+
+trap 'test $? = 0 || echo "$0 failed!" >& 2' 0
+radix=0
+awk=awk
+while getopts b:A:hV opt
+do
+	case $opt in
+		b)
+			expr x"$OPTARG" : x'[1-9][0-9]*$' > /dev/null
+			radix=$OPTARG
+			;;
+		A) awk=$OPTARG;;
+		h) exit_help;;
+		V) exit_version;;
+		*) false || exit
+	esac
+done
+shift `expr $OPTIND - 1 || :`
+$awk -f - -- "$@" << EOF || false
+	function vinternal(    i, al, c) {
 		for (vmodulus= 1; vmodulus + 1 > vmodulus; ) {
 			vmodulus+= vmodulus
 		}
 		vmodulus*= 0.5 # First bit is only implicit.
 		vshiftin= vmodulus * 0.5 # The bit shifted in by vlsr().
+		valphabet= "0123456789abcdefghijklmnopqrstuvwxyz"
+		al= length(valphabet)
+		for (i= 1; i <= al; ++i) {
+			vrevdigits[c= substr(valphabet, i, 1)]= i
+			vrevdigits[toupper(c)]= i
+		}
 	}
 
+	# <uint> may be omitted if <v> will be assigned to before use anyway.
 	function vinit(v, uint    , i) {
 		if (!vmodulus) vinternal()
 		for (i in v) delete v[i]
@@ -17,11 +88,7 @@ awk -f - -- "$@" << EOF && exit || false || exit
 		v[0]= uint
 	}
 
-	function vdump(v    , i, n) {
-		n= v["n"]
-		for (i= 0; i < n; ++i) printf "[%u]= %.0f\n", i, v[i]
-	}
-
+	# Both <dst> and <src> must already be initialized objects.
 	function vassign(dst, src    , i, ns, nd) {
 		nd= dst["n"]; ns= src["n"]
 		for (i= 0; i < ns; ++i) dst[i]= src[i]
@@ -101,24 +168,6 @@ awk -f - -- "$@" << EOF && exit || false || exit
 		return !!carry
 	}
 
-	function vpow(dst, ex    , mult) {
-		vnormalize(ex)
-		if (ex["n"] == 1 && ex[0] == 0) {
-			vinit(dst, 1) # dst^0 == 1.
-			return
-		}
-		vinit(mult, 1)
-		while (ex["n"] != 1 || ex[0] != 1) {
-			if (vlsr(ex)) {
-				# dst^(2*ex+1) == dst*(dst^(2*ex))
-				vmult(mult, dst)
-			}
-			# dst^(2*ex) == (dst*dst)^ex
-			vmult(dst, dst)
-		}
-		vmult(dst, mult)
-	}
-
 	# <dst> as well as <add> must be less than <mod>.
 	function vmodsum(dst, add, mod    , i, n, sum, carry, borrow) {
 		if (src["n"] > (n= mod["n"])) n= src["n"]
@@ -187,20 +236,31 @@ awk -f - -- "$@" << EOF && exit || false || exit
 		vinit(mult, 1)
 		# Reduce exponent until dst^1 == dst.
 		while (ex["n"] != 1 || ex[0] != 1) {
-			#print "dst= " v2str(dst) ", ex= " v2str(ex)
 			if (vlsr(ex)) {
 				# dst^(2*ex+1) == dst*(dst^(2*ex))
 				vmodmult(mult, dst, mod)
-			#	print "update mult factor= " v2str(mult)
 			}
 			# dst^(2*ex) == (dst*dst)^ex
 			vmodmult(dst, dst, mod)
-			#print "only squared: dst= " v2str(dst) ", new ex= " v2str(ex)
 		}
 		vmodmult(dst, mult, mod)
 	}
 
-	function v2str(v    , vn, i, j, k, n, o, b, carry, sum) {
+	function v2str( \
+		v, uint_radix_opt    , \
+		vn, i, j, k, n, o, b, carry, sum \
+	) {
+		if (!uint_radix_opt) {
+			uint_radix_opt= 10
+		} else if ( \
+			uint_radix_opt < 2 \
+			|| uint_radix_opt > length(valphabet) \
+		) {
+			die( \
+				"Unsupported output radix base " \
+				uint_radix_opt "!" \
+			);
+		}
 		vnormalize(v); vn= v["n"]
 		n= 0; o[n++]= 0
 		for (i= vn; i--; ) {
@@ -209,8 +269,11 @@ awk -f - -- "$@" << EOF && exit || false || exit
 				if (carry= b >= j) b-= j
 				for (k= 0; k < n; ++k) {
 					sum= o[k]
-					if (carry= (sum+= sum + carry) >= 10) {
-						sum-= 10
+					if ( \
+						carry= (sum+= sum + carry) \
+						>= uint_radix_opt \
+					) {
+						sum-= uint_radix_opt
 					}
 					o[k]= sum
 				}
@@ -218,37 +281,59 @@ awk -f - -- "$@" << EOF && exit || false || exit
 			}
 		}
 		sum= ""
-		for (k= n; k--; ) sum= sum o[k]
+		for (k= n; k--; ) sum= sum substr(valphabet, o[k] + 1, 1)
 		return sum
 	}
 
-	function vstr2v(dst, str    , i, sl, c, a) {
-		sl= length(str)
-		vinit(dst, 0)
-		for (i= 1; i <= sl; ++i) {
-			if ((c= substr(str, i, 1)) < "0" || c > "9") {
-				die("Invalid digit '" c "' in '" str "'!")
+	function vstr2v(dst, str, uint_radix_opt    , radix, i, sl, c, a) {
+		if (!uint_radix_opt) {
+			if (sub("^0[xX]", "", str)) uint_radix_opt= 16
+			else if (sub("^0[oO]", "", str)) uint_radix_opt= 8
+			else if (sub("^0[bB]", "", str)) uint_radix_opt= 2
+			else if (match(str, "^0[rR][1-9][0-9]*:")) {
+				uint_radix_opt= substr(str, RSTART, RLENGTH)
+				str= substr(str, RSTART + RLENGTH)
+				match(uint_radix_opt, "[1-9][0-9]*")
+				uint_radix_opt= 0 + substr( \
+					uint_radix_opt, RSTART, RLENGTH \
+				)
 			}
-			vassign(a, dst); vadd(a, a); vadd(a, a)
-			vadd(dst, a); vadd(dst, dst)
-			vinit(a, c + 0)
+		} else {
+			uint_radix_opt+= 0
+		}
+		if (!uint_radix_opt) uint_radix_opt= 10
+		vinit(radix, uint_radix_opt)
+		sl= length(str); vinit(dst, 0); vinit(a)
+		for (i= 1; i <= sl; ++i) {
+			if ( \
+				!(c= vrevdigits[substr(str, i, 1)]) \
+				|| c > uint_radix_opt \
+			) {
+				die( \
+					"Invalid digit '" substr(str, i, 1) \
+					"' in '" str "' for radix base " \
+					uint_radix_opt "!" \
+				)
+			}
+			vmult(dst, radix)
+			vinit(a, c - 1)
 			vadd(dst, a)
 		}
 	}
 
 	function die(msg) {
 		print msg > "/dev/stderr"
-		exit 1
+		exit 1 # Will be converted to false.
 	}
 
 	BEGIN {
 		if (ARGC < 4) {
 			die("Arguments: <base> <exponent> <modulus>!")
 		}
-		vstr2v(x, ARGV[1])
-		vstr2v(n, ARGV[2])
-		vstr2v(mod, ARGV[3])
+		vstr2v(x, ARGV[1], $radix)
+		vstr2v(n, ARGV[2], $radix)
+		vstr2v(mod, ARGV[3], $radix)
 		vmodexp(x, n, mod)
-		print v2str(x)
+		print v2str(x, $radix)
 	}
 EOF
